export const SOCKET_EVENTS = {
  // Connection & Handshake
  CONNECT: "connect",
  DISCONNECT: "disconnect",
  CONNECT_ERROR: "connect_error",

  // Room Lifecycle
  JOIN_ROOM: "JOIN_ROOM",
  LEAVE_ROOM: "LEAVE_ROOM",
  ROOM_STATE_UPDATE: "ROOM_STATE_UPDATE",
  USER_JOINED: "USER_JOINED",
  USER_LEFT: "USER_LEFT",

  // Lobby & Waiting Room
  REQUEST_JOIN_LOBBY: "REQUEST_JOIN_LOBBY",
  LOBBY_JOIN_REQUEST: "LOBBY_JOIN_REQUEST",
  ADMIN_ADMIT_USER: "ADMIN_ADMIT_USER",
  ADMIN_DENY_USER: "ADMIN_DENY_USER",
  LOBBY_APPROVED: "LOBBY_APPROVED",
  LOBBY_REJECTED: "LOBBY_REJECTED",

  // Media State & Signaling
  TOGGLE_MEDIA_STATE: "TOGGLE_MEDIA_STATE",
  PARTICIPANT_MEDIA_UPDATED: "PARTICIPANT_MEDIA_UPDATED",

  // Real-time Chat
  SEND_CHAT_MESSAGE: "SEND_CHAT_MESSAGE",
  NEW_CHAT_MESSAGE: "NEW_CHAT_MESSAGE",
};
